### ISSUE TITLE
Spellcheck

### ISSUE THREAD

**Issue by sgibson91** [sgibson91/sgibson91.github.io#60]
### Describe the bug

Fix typos in the website.

### TODO

- [ ] Fix genuine typos
- [ ] Add `wordlist.txt` of allowed spellings
- [ ] (Optional) Investigate `en_gb` setting for [spellcheck action](https://github.com/marketplace/actions/check-spelling-js-vue-html-markdown-text)
